{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lottoti-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: lottoti-tls
  issuerRef:
    name: {{ .Values.ingress.tls.issuerRef }}
    kind: ClusterIssuer
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: {{ .Values.global.domain }}
  dnsNames:
    - {{ .Values.global.domain }}
    - "api.{{ .Values.global.domain }}"
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lottoti
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuerRef }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.domain }}
        - "api.{{ .Values.global.domain }}"
      secretName: lottoti-tls
  {{- end }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.port }}
    - host: "api.{{ .Values.global.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.port }}
{{- end }}
