{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: lottoti-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lottoti.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | required ".Values.secrets.postgresPassword est requis" }}
  FLASK_SECRET_KEY: {{ .Values.secrets.flaskSecretKey | required ".Values.secrets.flaskSecretKey est requis" }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | required ".Values.secrets.jwtSecretKey est requis" }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripeSecretKey | default "sk_test_placeholder" }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secrets.stripeWebhookSecret | default "whsec_placeholder" }}
{{- end }}
